# Generated by Django 5.2.3 on 2025-06-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
